"""Configuration: TOML in, frozen dataclasses out.

Parsing and validation happen once, here, at the boundary. Everything
downstream receives already-valid values, so no other module needs to defend
against a missing key or a negative duration.
"""

from __future__ import annotations

import tomllib
from collections.abc import Mapping
from dataclasses import dataclass, field, replace
from pathlib import Path
from typing import Any, Literal, Self

DEFAULT_CONFIG_PATH = Path.home() / ".config" / "voice-kb" / "config.toml"

type DecodingMethod = Literal["greedy_search", "modified_beam_search"]


class ConfigError(ValueError):
    """Raised for a malformed config, with the offending key in the message."""


@dataclass(frozen=True, slots=True)
class HotkeyConfig:
    key_code: int = 186
    """evdev key code. 186 is ``KEY_F16`` -- the Keychron Q10 Pro's M4 key.

    Note this is the *evdev* code, not the X11 keycode (which is this + 8).
    """

    cancel_key_code: int | None = 1
    """evdev ``KEY_ESC``. ``None`` disables cancelling."""

    def __post_init__(self) -> None:
        if not 0 < self.key_code < 0x300:
            raise ConfigError(f"hotkey.key_code out of range: {self.key_code}")


@dataclass(frozen=True, slots=True)
class AudioConfig:
    sample_rate: int = 16000
    """Parakeet expects 16 kHz. Changing this requires a matching model."""

    preroll_ms: int = 250
    """Audio retained before the key goes down, so the first word is not clipped.

    Costs an always-open input stream. ``0`` disables it and the stream is
    opened lazily on keypress instead.
    """

    device: str | None = None
    """``None`` means the PipeWire/PulseAudio default source."""

    def __post_init__(self) -> None:
        if self.sample_rate <= 0:
            raise ConfigError(f"audio.sample_rate must be positive: {self.sample_rate}")
        if self.preroll_ms < 0:
            raise ConfigError(f"audio.preroll_ms must not be negative: {self.preroll_ms}")

    @property
    def preroll_frames(self) -> int:
        return self.sample_rate * self.preroll_ms // 1000


@dataclass(frozen=True, slots=True)
class AsrConfig:
    model_dir: Path = Path("models/parakeet-tdt-0.6b-v3-int8")
    num_threads: int = 6
    decoding: DecodingMethod = "modified_beam_search"

    hotwords_score: float = 1.5
    """Per-token bias for hotwords.

    Measured on this model: 1.5 fixes ``mkir`` -> ``mkdir``; 3.0 starts firing
    on unrelated audio; 6.0 rewrites ordinary words. Raise with care and
    re-run ``scripts/eval.py``.
    """

    vocabulary: tuple[str, ...] = ()
    """Words and phrases to bias toward. Written to a hotwords file at startup.

    Only used with ``modified_beam_search``; greedy decoding ignores it.
    """

    def __post_init__(self) -> None:
        if self.num_threads < 1:
            raise ConfigError(f"asr.num_threads must be >= 1: {self.num_threads}")
        if self.vocabulary and self.decoding != "modified_beam_search":
            raise ConfigError(
                "asr.vocabulary requires decoding = 'modified_beam_search'; "
                f"got {self.decoding!r}"
            )

    @property
    def encoder(self) -> Path:
        return self.model_dir / "encoder.int8.onnx"

    @property
    def decoder(self) -> Path:
        return self.model_dir / "decoder.int8.onnx"

    @property
    def joiner(self) -> Path:
        return self.model_dir / "joiner.int8.onnx"

    @property
    def tokens(self) -> Path:
        return self.model_dir / "tokens.txt"

    @property
    def bpe_vocab(self) -> Path:
        """Generated by ``scripts/build_hotwords.py``; not shipped with the model."""
        return self.model_dir / "bpe.vocab"


@dataclass(frozen=True, slots=True)
class TextConfig:
    strip_fillers: bool = True
    fillers: tuple[str, ...] = ("uh", "um", "erm", "hmm")
    """Removed only as standalone words, never as substrings."""

    replacements: Mapping[str, str] = field(default_factory=dict)
    """Exact, whole-word substitutions applied after decoding.

    Deliberately not fuzzy. Edit-distance matching on short tokens is what
    turned ``set`` into ``sed`` and ``reset`` into ``rust`` in the tool this
    project replaced. Prefer ``asr.vocabulary`` -- biasing the beam beats
    rewriting the output.
    """

    trailing_space: bool = False


@dataclass(frozen=True, slots=True)
class PasteConfig:
    default: str = "ctrl+v"
    per_window_class: Mapping[str, str] = field(
        default_factory=lambda: {"Alacritty": "ctrl+shift+v"}
    )
    """Keyed by X11 ``WM_CLASS``; terminals need shift."""

    restore_delay_ms: int = 150
    """How long to wait before putting the previous clipboard contents back."""

    def combo_for(self, window_class: str | None) -> str:
        if window_class is None:
            return self.default
        return self.per_window_class.get(window_class, self.default)


@dataclass(frozen=True, slots=True)
class OverlayConfig:
    enabled: bool = True
    width: int = 420
    height: int = 96
    margin_px: int = 32
    """Gap between the overlay and the bottom edge of the output."""

    follow_focus: bool = True
    """Place the overlay on the output holding the focused window."""


@dataclass(frozen=True, slots=True)
class Config:
    hotkey: HotkeyConfig = field(default_factory=HotkeyConfig)
    audio: AudioConfig = field(default_factory=AudioConfig)
    asr: AsrConfig = field(default_factory=AsrConfig)
    text: TextConfig = field(default_factory=TextConfig)
    paste: PasteConfig = field(default_factory=PasteConfig)
    overlay: OverlayConfig = field(default_factory=OverlayConfig)

    @classmethod
    def load(cls, path: Path | None = None) -> Self:
        """Read TOML from ``path``, falling back to defaults if it is absent."""
        target = path or DEFAULT_CONFIG_PATH
        if not target.exists():
            return cls()
        try:
            raw = tomllib.loads(target.read_text(encoding="utf-8"))
        except tomllib.TOMLDecodeError as e:
            raise ConfigError(f"{target}: {e}") from e
        return cls.from_mapping(raw, base_dir=target.parent)

    @classmethod
    def from_mapping(cls, raw: Mapping[str, Any], base_dir: Path | None = None) -> Self:
        known = {"hotkey", "audio", "asr", "text", "paste", "overlay"}
        if unknown := set(raw) - known:
            raise ConfigError(f"unknown config section(s): {', '.join(sorted(unknown))}")

        return cls(
            hotkey=_build(HotkeyConfig, raw.get("hotkey", {}), "hotkey"),
            audio=_build(AudioConfig, raw.get("audio", {}), "audio"),
            asr=_build(
                AsrConfig,
                _resolve_model_dir(raw.get("asr", {}), base_dir),
                "asr",
                tuple_fields=("vocabulary",),
            ),
            text=_build(TextConfig, raw.get("text", {}), "text", tuple_fields=("fillers",)),
            paste=_build(PasteConfig, raw.get("paste", {}), "paste"),
            overlay=_build(OverlayConfig, raw.get("overlay", {}), "overlay"),
        )

    def with_model_dir(self, model_dir: Path) -> Self:
        """Override the model location, e.g. from a CLI flag."""
        return replace(self, asr=replace(self.asr, model_dir=model_dir))


def _resolve_model_dir(section: Mapping[str, Any], base_dir: Path | None) -> Mapping[str, Any]:
    """Make a relative ``model_dir`` relative to the config file, not the cwd."""
    if "model_dir" not in section:
        return section
    model_dir = Path(str(section["model_dir"])).expanduser()
    if not model_dir.is_absolute() and base_dir is not None:
        model_dir = base_dir / model_dir
    return {**section, "model_dir": model_dir}


def _build[T](
    kind: type[T],
    section: Mapping[str, Any],
    name: str,
    tuple_fields: tuple[str, ...] = (),
) -> T:
    """Construct a config dataclass, converting lists to tuples and reporting
    unknown keys against the section they appeared in."""
    fields = {f for f in kind.__dataclass_fields__}  # type: ignore[attr-defined]
    if unknown := set(section) - fields:
        raise ConfigError(f"unknown key(s) in [{name}]: {', '.join(sorted(unknown))}")
    values = {
        k: tuple(v) if k in tuple_fields and isinstance(v, list) else v
        for k, v in section.items()
    }
    try:
        return kind(**values)
    except TypeError as e:
        raise ConfigError(f"[{name}]: {e}") from e
